name: terrain-gen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal>=3.7
  - networkx>=3.4.2
  - numpy>=1.24
  - rasterio>=1.3
  - trimesh>=3.23
  - pyproj>=3.6
  - scipy>=1.15
  - pip
