name: world-to-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - rasterio
  - gdal
  - scipy
  - matplotlib
  - tqdm
  - cadquery
  - geopy
  - requests
  - rich>=13.0.0
  - scikit-image
  - pip
  - pip:
    - git+https://github.com/JustinSDK/cqMore
    - meshlib
