name: world-to-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - rasterio
  - gdal
  - scipy
  - matplotlib
  - geopy
  - requests
  - rich>=13.0.0
  - scikit-image
  - shapely
  - pyyaml
  - pip
  - pip:
    - meshlib
