version: 1
name: bay_area
output_prefix: bay_area
bounds: [-122.67, 37.22, -121.75, 38.18]

elevation_source:
  type: geotiff
  topo_dir: topo
  file: output_USGS10m.tif

terrain:
  base_height: 2500
  elevation_multiplier: 3.5
  downsample_factor: 1
  water_threshold: 1
  decimate: false

buildings:
  enabled: true
  timeout: 120
  extract:
    max_building_distance_meters: 35
  generate:
    building_height_multiplier: 3.5
    min_building_height: 100

output:
  directory: .


