version: 1
name: dc
output_prefix: dc
bounds: [-77.0728342158, 38.8349886875, -76.9620071625, 38.9178722916]

elevation_source:
  type: geotiff
  topo_dir: topo
  file: USGS_one_meter_x32y431_MD_VA_Sandy_NCR_2014.tif

terrain:
  base_height: 250
  elevation_multiplier: 3.5
  downsample_factor: 1
  water_threshold: 0
  force_refresh: false
  decimate: false

buildings:
  enabled: true
  timeout: 120
  extract:
    force_refresh: false
    max_building_distance_meters: 30
  generate:
    building_height_multiplier: 1
    min_building_height: 10

output:
  directory: .


