version: 1
name: newyork
output_prefix: newyork
bounds: [-74.1687, 40.5295, -73.7979, 40.9166]

elevation_source:
  type: srtm
  topo_dir: topo

terrain:
  base_height: 500
  elevation_multiplier: 3
  downsample_factor: 1
  water_threshold: 1

buildings:
  enabled: false

output:
  directory: .


