version: 1
name: sf_fidi
output_prefix: sf_fidi
bounds: [-122.42846, 37.77723, -122.37645, 37.81792]

elevation_source:
  type: geotiff
  topo_dir: topo
  # Use all SF-related tiles present; let the code auto-filter by bounds
  glob: "USGS_1M_10_*_CA_SanFrancisco_B23.tif"

terrain:
  base_height: 150
  elevation_multiplier: 1
  downsample_factor: 1
  water_threshold: 1
  adaptive_tolerance_z: 10.0
  adaptive_max_gap_fraction: 0.001
  adaptive_max_sampled_rows: 10000
  adaptive_max_sampled_cols: 10000
  split_at_water_level: true

buildings:
  enabled: true
  extract:
    max_building_distance_meters: 0
  generate:
    building_height_multiplier: 1
    min_building_height: 25

output:
  directory: .


