version: 1
name: sf_full
output_prefix: sf_full
bounds: [-122.521878,37.707039,-122.352077,37.838749]

global:
  scale_max_length_mm: 225.0

base:
  height: 20.0

elevation_source:
  type: geotiff
  topo_dir: topo
  # Use all SF-related tiles present; let the code auto-filter by bounds
  glob: "USGS_1M_10_*.tif"

terrain:
  elevation_multiplier: 1
  downsample_factor: 10
  water_threshold: 1
  adaptive_tolerance_z: 10.0
  adaptive_max_gap_fraction: 0.001
  adaptive_max_sampled_rows: 10000
  adaptive_max_sampled_cols: 10000
  split_at_water_level: true

buildings:
  enabled: true
  extract:
    max_building_distance_meters: 0
  generate:
    building_height_multiplier: 1
    min_building_height: 25

tiling:
  rows: 3
  cols: 3

output:
  directory: ./outputs/sf_full


